[packages]

[packages.siafi-2026]
path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2026/main/datapackage.json"
token = "GH_TOKEN"

[packages.aux-classificadores]
path = "https://raw.githubusercontent.com/splor-mg/dados-aux-classificadores/main/datapackage.json"
