[theme]
base="light"
primaryColor="#1b5e20"         # Verde (padr√£o Governo MG pode ajustar)
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#222222"
font="sans serif"

[client]
showErrorDetails = false

[server]
runOnSave = true

[deprecation]
showfileUploaderEncoding = false