# .streamlit/config.toml
[theme]
primaryColor = "#0072B5"  # Azul meio institucional
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true
