[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1tw3d8R2Pv8w771K7_zBkV_vKROQuXF-qKZVhQoXkIJY/edit?gid=0#gid=0"
worksheet = "Página1"      # Nome da aba (verifique se é esse mesmo)

# Cole abaixo o conteúdo do seu arquivo JSON baixado do Google
type = "service_account"
project_id = "propag-monitoramento"
private_key_id = "6c39d6263fdf05172c0a30fed79a40cbe941ea3f"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC4cjNJNxOiLtQ+\nLkLEQsDyBqQf01azJ45ww3sA7JwtFNPBYs8T304MkMzAx1afHLWM/yuMrET40A4q\n9w7GXFjtVqXdcrOvU1hFMo4kAEXW11Pu9UVOcANab94cjrWk+ZqFfLTWUjEqfAnu\n4FlH4F3ldvkMxdzAzUCNtOaS0+oweDG5dM4cePxwO7rpLKFHRLOP6/v/T8KZjSjy\nmGJLBEd02w0FAYcTDW2f3d8KZexQEgRr1raZDhVOT8wawQjS+Doh9f9S9F4abYoF\niTOmwdBZy0RVRr+GVxWcd1CVcn+t5BXk7fA+1mJW0+72S8bhggqXaFRwtgkqP30o\n4kgkPIldAgMBAAECggEABgTQuSqt5DNIL3639jke4hWECAMbnsMau4G8Dq9vviXF\nKHrdAJT2eBg60SjnXCFjSxT8B94tnLtM+N+uA7OzqkZNbzi9wYE1nFNdgZrJlV4g\nRYr/sJGc5sN2CXBwArlOQCMoDYi4ohiBG7+R+kUPSeI4l08/m03C+45FWNHeq76i\n4PSKIl/40Ou9LRWhMjyFechIBnVqf2ixvyie0v9Di1+eF4KUzoFYvb78ApWa7y0I\nOkcSdVCaUt8XnWxG+7Ho1y7wYJ1PkxkL9TIKIAlfUyS7emLyB1btdqfKc6hhrWYa\nFGiFsles2vYLTrQhZSK3btDyeNwSk1KhCoF1+OLzywKBgQDhPdvHw1IndjjimK6i\n6O+5+8ASTWt448mhENHzkX2ofXFMqQmCngI+afdQNc/9puhzXU46r6vwqVes/A0v\nIZtVwd5nXucUHDmMIXyHxtRYKfbwGrSztQRAE996JPLDQM5M1eJFvzxvndJImZql\nZn2Uj2sqboJa5tm7EZpHj3xJzwKBgQDRoi9oNj1RrbKyQiwuBCbV/XQ15BqpNkbZ\nrKL2u8z0G/as73k+m23KtQWmi6e7wgmupvEKNJglaikdfFt9+vj2HPxeptowwc2H\nTKqh+T7aUj5CQkHQ3e+YVSY9uUtK12uh/BkkW6U1mYUNxLZMhrJzEp/XYBxMCqIC\nAhZ6zULBEwKBgQCxRDfGXcg4WmimnTdD60NQAfvF67xbZhp3cn9py+UzR5Z1mMtt\nSuHFMSx8qf1JSaTDtnks4rjVLNFdyPivUSmpMmzQufXu88+uo2QYj7jqsgwwJzR0\nAlCYBYvp205bsJMsEWCFN95ekby/enQlHCZVVxImUNayp+BPw6jCDQDqLQKBgQCp\nK3+kUnkDa+/T6JCshc8tSv636p8VRGbCjI1qHT2VFOfowMwQGO/t8E1iDDtMypZz\nqebEfJL3RodtcwiGTr0QJ24FmBJl3E/Wyqi8U15EYrA5WiywuBj8zmIw11IKUHNc\nYguMCqT07zGvXbpbYSuqrzHsZXQQbVg11Kd9bB1dnwKBgQCL2UJzE70hVu4kWaps\nU5E02yfvzujHIGlvFQBSPReN3DK56uHgrUmL81AR+uONtgQK43Qzgy++26AG/PUs\nljiOuzc8IooniYJSuFclnkOjA8MD04wiQq7zcAsW7YfvMfml6Asejm9Tm+KqWe/W\nb0q8Q+BsxoWqpm7EL8ffzYek2w==\n-----END PRIVATE KEY-----\n"
client_email = "propag-monitoramento@propag-monitoramento.iam.gserviceaccount.com"
client_id = "100444564999145262370"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/propag-monitoramento%40propag-monitoramento.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[auth]
cookie_name = "propag_monitoramento"
cookie_key = "qavq-vftGw0fM0sKMBlyJ2-cdD-QLvyLV0v6g-bnFtWgOWJg27XkFWDM4QG8RoejNjGzqoL57D3h6gK6WBMhig"
cookie_expiry_days = 3

[auth.credentials.usernames.admin]
name = "Admin - Central"
email = "admin@org.br"
password = "$2b$12$cmaSjEj3okXpfDbDW85cNO4JpyXvfKNI.JI/85iyUuCeLYGDTvs3e"

[auth.credentials.usernames.pmmg]
name = "PMMG"
email = "pmmg@org.br"
password = "$2b$12$nG.KmD56FXBrjcfcM2PWX.zZcqBx3MdxIvtGi2SH5iNOeHF3wV/hS"

[auth.credentials.usernames.cbmmg]
name = "CBMMG"
email = "cbmmg@org.br"
password = "$2b$12$k3VM0Jl1jCuBsUQCnq1XZ.8f4bYSy1CDTnJ0sZteuR.PYYALRt9gi"

[auth.credentials.usernames.der]
name = "DER"
email = "der@org.br"
password = "$2b$12$GPnfQc144AtEkcEHBYoTNuXGWm7P8.0Y5/p/n9Dp5gClAQwbHycSi"

[auth.credentials.usernames.seinfra]
name = "SEINFRA"
email = "seinfra@org.br"
password = "$2b$12$gDx2hM.cZ6/0PGMSAtrBSuWVJlM1tf9eVgIglOdqlp7JiyFhSjP42"

[auth.credentials.usernames.pcmg]
name = "PCMG"
email = "pcmg@org.br"
password = "$2b$12$GWTn1zS7dWO5osaYoNlpLObLvoVIGs/S0l19s7hyygpQG/ie6TBNC"

[auth.credentials.usernames.sejusp]
name = "SEJUSP"
email = "sejusp@org.br"
password = "$2b$12$zpBpwFCxqqoslMf8E418Xuz6fIFQ8Ql2N1OLKumCSo0/cHokHq7DC"

# ======================================================================
# 3) NOVO: RBAC — mapeamento username -> UOs
#    Use "*" para admin (acesso total) e listas de uo_cod para órgãos.
# ======================================================================
[rbac]
admin   = ["*"]            # acesso total (admin)
pmmg    = [1251]           # PMMG
cbmmg   = [1401]           # CBMMG
der     = [2301, 4381]     # DER + FUNTRANS
seinfra = [1301]           # SEINFRA
pcmg    = [1511]           # PCMG
sejusp  = [1451]           # SEJUSP
